# Generated by Django 3.1.7 on 2021-03-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Обрабатывается'), (2, 'Подтвержден'), (3, 'Оплачен'), (4, 'Отправлен'), (5, 'Доставлен'), (6, 'Отменен')], default=1),
        ),
    ]
