# Generated by Django 3.1.7 on 2021-03-12 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='order',
        ),
        migrations.AddField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='shop.product'),
            preserve_default=False,
        ),
    ]
